"""Shared model choice constants live here so that models, serializers and
the admin all reference a single source of truth."""


# User roles
PATIENT = "PATIENT"
DOCTOR = "DOCTOR"
ADMIN = "ADMIN"

ROLE_CHOICES = [
    (PATIENT, "Patient"),
    (DOCTOR, "Doctor"),
    (ADMIN, "Admin"),
]


# Appointment status
APPOINTMENT_STATUS_PENDING = "PENDING"
APPOINTMENT_STATUS_CONFIRMED = "CONFIRMED"
APPOINTMENT_STATUS_COMPLETED = "COMPLETED"
APPOINTMENT_STATUS_CANCELLED = "CANCELLED"

APPOINTMENT_STATUS_CHOICES = [
    (APPOINTMENT_STATUS_PENDING, "Pending"),
    (APPOINTMENT_STATUS_CONFIRMED, "Confirmed"),
    (APPOINTMENT_STATUS_COMPLETED, "Completed"),
    (APPOINTMENT_STATUS_CANCELLED, "Cancelled"),
]


# Appointment type
APPOINTMENT_TYPE_IN_PERSON = "IN_PERSON"
APPOINTMENT_TYPE_ONLINE_CHAT = "ONLINE_CHAT"
APPOINTMENT_TYPE_ONLINE_VIDEO = "ONLINE_VIDEO"

APPOINTMENT_TYPE_CHOICES = [
    (APPOINTMENT_TYPE_IN_PERSON, "In-Person"),
    (APPOINTMENT_TYPE_ONLINE_CHAT, "Online Chat"),
    (APPOINTMENT_TYPE_ONLINE_VIDEO, "Online Video"),
]


# Payment status
PAYMENT_STATUS_PENDING = "PENDING"
PAYMENT_STATUS_PAID = "PAID"
PAYMENT_STATUS_FAILED = "FAILED"
PAYMENT_STATUS_REFUNDED = "REFUNDED"

PAYMENT_STATUS_CHOICES = [
    (PAYMENT_STATUS_PENDING, "Pending"),
    (PAYMENT_STATUS_PAID, "Paid"),
    (PAYMENT_STATUS_FAILED, "Failed"),
    (PAYMENT_STATUS_REFUNDED, "Refunded"),
]


# Payment type (when patient pays)
PAYMENT_TYPE_NOW = "PAY_NOW"
PAYMENT_TYPE_AFTER = "PAY_AFTER"

PAYMENT_TYPE_CHOICES = [
    (PAYMENT_TYPE_NOW, "Pay Now"),
    (PAYMENT_TYPE_AFTER, "Pay After"),
]


# Subscription status
SUBSCRIPTION_STATUS_ACTIVE = "ACTIVE"
SUBSCRIPTION_STATUS_EXPIRED = "EXPIRED"
SUBSCRIPTION_STATUS_CANCELLED = "CANCELLED"

SUBSCRIPTION_STATUS_CHOICES = [
    (SUBSCRIPTION_STATUS_ACTIVE, "Active"),
    (SUBSCRIPTION_STATUS_EXPIRED, "Expired"),
    (SUBSCRIPTION_STATUS_CANCELLED, "Cancelled"),
]
