# Generated by Django 6.0.7 on 2026-07-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_unique_active_appointment_per_doctor_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('IN_PERSON', 'In-Person'), ('ONLINE_CHAT', 'Online Chat'), ('ONLINE_VIDEO', 'Online Video')], default='IN_PERSON', max_length=15),
        ),
    ]
