# Generated by Django 6.0.7 on 2026-07-17 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_appointment_type'),
        ('doctors', '0005_doctorprofile_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_appointment_per_doctor_slot',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('scheduled_at__isnull', False), ('status__in', ['CONFIRMED'])), fields=('doctor', 'scheduled_at'), name='unique_confirmed_appointment_per_doctor_slot'),
        ),
    ]
