# Generated by Django 6.0.7 on 2026-07-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_availability_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='online_consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
