# Generated by Django 6.0.7 on 2026-07-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorprofile_online_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
