# Generated by Django 6.0.7 on 2026-07-16 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'system'), ('user', 'user'), ('assistant', 'assistant'), ('tool', 'tool')], max_length=10)),
                ('content', models.TextField()),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('tool_args', models.JSONField(blank=True, null=True)),
                ('tool_call_id', models.CharField(blank=True, max_length=100)),
                ('proposal_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.agentsession')),
            ],
            options={
                'db_table': 'agent_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='agent_messa_user_id_942882_idx')],
            },
        ),
    ]
