# Generated by Django 6.0.7 on 2026-07-15 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_remove_appointment_unique_active_appointment_per_doctor_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=12)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, default='', max_length=100)),
                ('checkout_url', models.URLField(blank=True, default='')),
                ('receipt_url', models.URLField(blank=True, default='')),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.appointment')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['appointment', 'status'], name='payments_pa_appoint_6c6442_idx'), models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__6fe52c_idx')],
            },
        ),
    ]
