# Generated by Django 6.0.7 on 2026-07-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscriptionplan_doctorsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
